# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Build Artifacts
on:
  - push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Maven package 
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mvn -PbuildKar clean install -X -Dmaven.test.skip=true \
          --settings .github/workflows/maven-settings.xml \
          --file pom.xml
